Dev address book
LiliiaMykhaliuk/Address-book pull request #1
Opened 2022-06-09 21:19 UTC by liliamyhaliuk

This programm is not done yet, because I have questions for you, but i would like you to look on my code before our meeting.

2022-06-10 07:52 UTC, auraz requested changes

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +            return self.address_book[contact_group].get(contact_name, "Contact doesn't exist.")
Please ensure we go through all groups

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +        while True:
Change while True loop into the for loop (optional)

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +        """Function search for an instance of the contact with passed name"""
Add search for lowercase name

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +            mod_contact = res
not needed

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +                if mod_attr == "name":
pattern dispatcher.

```
actions = {
"name": change_name,
"email": change_email,
...
}
```

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +                        if self.address_book[key].get(mod_contact.name) is not None:
mod_contact.name always exist, because we already found it.

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +                    USER_INPUT = input('Name was modified. Do you want to modified another field? (yes/no): ' )
please move input_text into the constant

2022-06-10 07:52 UTC, auraz commented on class_address_book.py
> +                    mod_contact.email = input("Enter new email: ")
prefix = "Entre new {}".
input(prefix.format(mod_attr))

2022-06-10 07:52 UTC, auraz commented on main_menu.py
> +    if action == "1":
please rewrite using dispatcher.

2022-06-10 07:52 UTC, auraz commented on main_menu.py
> +    new_address_book = AdressBook()
and create new empty file

2022-06-14 23:28 UTC, liliamyhaliuk commented on class_address_book.py
> +            return self.address_book[contact_group].get(contact_name, "Contact doesn't exist.")
Done

2022-06-14 23:29 UTC, liliamyhaliuk commented on class_address_book.py
> +        """Function search for an instance of the contact with passed name"""
I added this feature everywhere so now it doesn't depends on case. Thank you!

2022-06-14 23:30 UTC, liliamyhaliuk commented on class_address_book.py
> +            mod_contact = res
Deleted it. Thnak you!

2022-06-14 23:30 UTC, liliamyhaliuk commented on class_address_book.py
> +                if mod_attr == "name":
Done!

2022-06-14 23:33 UTC, liliamyhaliuk commented on class_address_book.py
> +                        if self.address_book[key].get(mod_contact.name) is not None:
This condition is here so that we can loop through all groups in address book and find the correct group (key) that we have to work with.

2022-06-14 23:35 UTC, liliamyhaliuk commented on class_address_book.py
> +                    mod_contact.email = input("Enter new email: ")
I did formatting in another way  -  f" {} aaa", if it's okay

2022-06-14 23:36 UTC, liliamyhaliuk commented on main_menu.py
> +    if action == "1":
Done

2022-06-15 07:05 UTC, auraz requested changes
Please test program with different inputs (empty name, and so on)

2022-06-15 07:05 UTC, auraz commented on class_address_book.py
> +        else:
Check if this else is needed.

2022-06-15 07:05 UTC, auraz commented on class_address_book.py
> +                break
Change break to return

2022-06-15 07:05 UTC, auraz commented on main_menu.py
> +        new_address_book.address_book = new_address_book_dict
Use constructor instead

2022-06-15 07:05 UTC, auraz commented on main_menu.py
> +    except KeyError:
Run program and test, should be Type Error

2022-06-22 21:44 UTC, liliamyhaliuk commented on class_address_book.py
> +    address_book = {
Done. Thank you!

2022-06-22 21:46 UTC, liliamyhaliuk commented on class_address_book.py
> +        else:
I changed this "else" for error counter so please check if this is still an issue?

2022-06-23 06:00 UTC, auraz requested changes

2023-08-10 14:15 UTC, merged